version: '3.8'

services:
  nginx:
    depends_on:
      - backend
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./static:/static
      - ./nginx.conf:/etc/nginx/conf.d
  backend:
    depends_on:
      - database
      - migration
      - collectstatic
    image: dockerhw4
    build:
      context: simple_crud
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - ./static:/static
    networks:
      - backend
  collectstatic:
    image: dockerhw4
    build: .
    command: python manage.py collectstatic
    volumes:
      - ./static:/static
  migration:
    image: dockerhw4
    command: python manage.py migrate --noinput
    env_file:
      - .env
    depends_on:
      - database
#        condition: service_healthy
  database:
    image: postgres:11.0-alpine
    environment:
      DEBUG: 'True'
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - backend
#    healthcheck:
#      test: ["CMD-SHELL","pg_isready -U postgres"]
#      interval: 5s
#      timeout: 5s
#      retries: 5
volumes:
  pg-data:
networks:
  backend:



