version: '3.9'

services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST : 'localhost'
    volumes:
      - ./data/db:/var/lib/postgresql/data
  backend:
    container_name: backend
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./static:/static
    depends_on:
      - database
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/static
      - ./nginx.conf:/etc/nginx/conf.d
    depends_on:
      - backend
volumes:
  postgres_data: