version: '3.9'

services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
  migration:
    image: dockerhw4
    command: python manage.py migrate --noinput
    links:
      - database
    depends_on:
      - database
  collectstatic:
    image: dockerhw4
    build: .
    command: python manage.py collectstatic --noinput
    volumes:
      - ./static:/static
  backend:
    image: dockerhw4
    build:
      context: simple_crud
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./static:/static
    depends_on:
      - migration
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/static
      - ./nginx.conf:/etc/nginx/conf.d
    depends_on:
      - backend
volumes:
  postgres_data: