name: Docker-image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          HEROKU_APP_NAME: ${{secrets.HEROKU_APP_KEY}}
        run: heroku container:login
      - name: Build the Docker image
        run: docker build -t web:latest ./simple_crud
      - name: Push the Docker image to Heroku
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: |
          heroku container:push web --app ${{secrets.HEROKU_APP_NAME}} web
          heroku container:release web --app ${{secrets.HEROKU_APP_NAME}} web
          heroku ps:scale web=1 -a ${{secrets.HEROKU_APP_NAME}}

