name: Docker-image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: docker login --username _ --password=${{secrets.HEROKU_API_KEY}} registry.heroku.com
      - name: Build the Docker image
        run: docker build -t web ./simple_crud
      - name: Push the Docker image to Heroku
        env:
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
        run: |
          docker tag web:latest registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/web
          docker push registry.heroku.com/${{secrets.HEROKU_APP_NAME}}/web
          heroku container:release web -a=${{secrets.HEROKU_APP_NAME}}
          heroku ps:scale my_app = 1 -a ${{secrets.HEROKU_APP_NAME}}

